import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, Bell, Camera, CheckCircle2, CloudRain, Droplets, Gauge, LayoutDashboard, Map, Menu, Moon, Radio, RefreshCw, Settings, Shield, Sun, Thermometer, Waves, Wind, Flame } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from './services/api'

const navItems = [['overview','Overview',LayoutDashboard],['sensors','Live Sensors',Activity],['risks','Risk Intelligence',Shield],['forecast','6-Hour Warning',Gauge],['camera','Camera Vision',Camera],['alerts','Alert Center',Bell],['reports','Reports',Radio],['map','Monitoring Map',Map],['settings','Settings',Settings]]
const metrics = [['Temperature','temperature','°C',Thermometer,'amber'],['Humidity','humidity','%',Droplets,'blue'],['Pressure','pressure','hPa',Wind,'violet'],['Rainfall','rainfall','mm/hr',CloudRain,'cyan'],['Water level','water_level','cm',Waves,'blue'],['Water rise','water_rise','cm',Waves,'indigo'],['Soil moisture','soil_moisture','%',Activity,'green'],['Tilt change','tilt_change','°',Gauge,'orange'],['MQ2 smoke','mq2_raw','raw',Flame,'red'],['MQ135 gas','mq135_raw','raw',Wind,'purple']]
const riskItems = [['Flood','flood_risk','flood_status',Waves],['Landslide','landslide_risk','landslide_status',Activity],['Air / gas','air_gas_risk','mq135_status',Wind],['Overall hazard','overall_risk','overall_status',Shield]]
const value = (v, digits=1) => v === null || v === undefined || v === '' ? 'N/A' : typeof v === 'number' ? v.toFixed(digits) : String(v)
const formatTime = v => { if (!v) return 'N/A'; const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}) }
const statusClass = v => String(v || 'N/A').toLowerCase().replace(/\s+/g,'-')

function Sidebar({ active, setActive, online, device, alertCount, mobileOpen }) {
  return <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><span/><span/><span/></div><div><strong>CLOUDGUARD</strong><small>ENVIRONMENTAL INTELLIGENCE</small></div></div><div className="eyebrow sidebar-label">OPERATIONS</div><nav>{navItems.map(([id,label,Icon]) => <button className={active===id?'nav-item active':'nav-item'} key={id} onClick={()=>setActive(id)}><Icon size={17}/><span>{label}</span>{id==='alerts'&&alertCount>0&&<b>{alertCount}</b>}</button>)}</nav><div className="sidebar-node"><span className="eyebrow">ACTIVE NODE</span><strong>{device||'N/A'}</strong><span className={online?'online-text':'offline-text'}>{online?'● ONLINE':'○ OFFLINE'}</span></div><div className="sidebar-footer"><span><CheckCircle2 size={14}/> Secure monitoring channel</span><small>BACKEND / FIREBASE</small></div></aside>
}
function Header({ active, backendOnline, lastSeen, onMenu, theme, setTheme }) { const title=navItems.find(x=>x[0]===active)?.[1]||'Overview'; return <header className="topbar"><button className="icon-button mobile-only" onClick={onMenu} aria-label="Open navigation"><Menu size={20}/></button><div><span className="eyebrow">CLOUDGUARD / LIVE OPERATIONS</span><h1>{title}</h1><p>Environmental intelligence and proactive early warning</p></div><div className="topbar-actions"><span className={backendOnline?'connection online':'connection'}><span/>{backendOnline?'Backend Online':'Backend Offline'}</span><div className="sync"><span>LAST SYNC</span><strong>{formatTime(lastSeen)}</strong></div><button className="icon-button" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Switch theme">{theme==='dark'?<Moon size={17}/>:<Sun size={17}/>}</button></div></header> }
function MetricCard({ item, data, online }) { const [label,key,unit,Icon,tone]=item; return <article className="metric-card"><div className={`metric-icon ${tone}`}><Icon size={18}/></div><div><span>{label}</span><strong>{online?value(data?.[key]):'N/A'}</strong><small>{unit}</small></div><em className={online?'status normal':'status'}>{online?'NORMAL':'NO DATA'}</em></article> }
function RiskCard({ item, data, online }) { const [label,riskKey,statusKey,Icon]=item; const score=online&&typeof data?.[riskKey]==='number'?data[riskKey]:null; return <article className="risk-card"><div className="risk-card-top"><div className="metric-icon blue"><Icon size={18}/></div><span className={`badge ${statusClass(online?data?.[statusKey]:'N/A')}`}>{online?data?.[statusKey]||'N/A':'N/A'}</span></div><span className="eyebrow">{label}</span><strong>{score===null?'N/A':value(score,0)}<small>/100</small></strong><div className="meter"><span style={{width:`${score??0}%`}}/></div></article> }
function SectionTitle({ eyebrow,title,detail }) { return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{detail}</p></div></div> }
function EmptyState({ children }) { return <div className="empty-state">{children}</div> }
function Reports() {
  const [filters, setFilters] = useState({ incident: 'All Incidents', severity: 'all', device_id: 'all', location: 'All Zones', start: '', end: '' })
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const query = new URLSearchParams(Object.entries(filters).filter(([, v]) => v && v !== 'all' && v !== 'All Incidents' && v !== 'All Zones')).toString()
  const generate = async () => { setLoading(true); setError(''); try { setReport(await api.get(`/api/reports/incident${query ? `?${query}` : ''}`)) } catch (e) { setError(e.message || 'Unable to generate report') } finally { setLoading(false) } }
  const exportReport = format => { const suffix = query ? `&${query}` : ''; window.location.href = `${api.baseUrl}/api/reports/export?format=${format}${suffix}` }
  return <section className="page-content"><SectionTitle eyebrow="INCIDENT EVIDENCE" title="Reports" detail="Generate evidence from real sensor, alert, and camera history."/><div className="report-controls">{[['incident','Incident',['All Incidents','Flood Risk','Landslide Risk','Air Quality Risk']],['severity','Severity',['all','NORMAL','WATCH','WARNING','CRITICAL']],['device_id','Device',['all','CG01','CG02','CG03','CG04']],['location','Location',['All Zones','Zone A']]].map(([key,label,options])=><label key={key}><span className="eyebrow">{label}</span><select value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{options.map(option=><option key={option}>{option}</option>)}</select></label>)}<label><span className="eyebrow">START</span><input type="datetime-local" value={filters.start} onChange={e=>setFilters({...filters,start:e.target.value})}/></label><label><span className="eyebrow">END</span><input type="datetime-local" value={filters.end} onChange={e=>setFilters({...filters,end:e.target.value})}/></label><button className="refresh-button" onClick={generate} disabled={loading}>{loading?'Generating...':'Generate report'}</button></div>{error&&<div className="error-banner"><AlertTriangle size={16}/>{error}</div>}{report&&<div className="report-output"><div className="report-head"><div><span className="eyebrow">{report.incident}</span><h2>{report.summary}</h2></div><span className={`badge ${statusClass(report.severity)}`}>{report.severity}</span></div><div className="report-kpis">{[['Peak rainfall',report.peak_rainfall,'mm/hr'],['Peak water',report.peak_water_level,'cm'],['Maximum risk',report.maximum_risk,'/100'],['Duration',report.duration,'']].map(([label,v,unit])=><div key={label}><span className="eyebrow">{label}</span><strong>{v ?? 'N/A'} {unit}</strong></div>)}</div><div className="report-columns"><div><h3>Sensor evidence</h3>{report.sensor_evidence?.length?<ul>{report.sensor_evidence.map((item,i)=><li key={i}>{item}</li>)}</ul>:<EmptyState>No sensor evidence available.</EmptyState>}</div><div><h3>Alert history</h3>{report.alert_history?.length?<ul>{report.alert_history.map((item,i)=><li key={i}>{item}</li>)}</ul>:<EmptyState>No alerts available.</EmptyState>}</div><div><h3>Camera evidence</h3>{report.camera_evidence?.length?<ul>{report.camera_evidence.map((item,i)=><li key={i}>{item}</li>)}</ul>:<EmptyState>No camera evidence available.</EmptyState>}</div></div><div className="report-actions"><button onClick={()=>exportReport('json')}>Export JSON</button><button onClick={()=>exportReport('csv')}>Export CSV</button><button onClick={()=>exportReport('pdf')}>Export PDF</button></div></div>}</section>
}
function Content({ active,data,online,history,alerts,forecast,camera,devices,refresh }) {
  if(active==='camera') return <section className="page-content"><SectionTitle eyebrow="FIELD EVIDENCE" title="Camera Vision" detail="Visual confirmation from the ESP32-CAM."/><div className="camera-panel"><div className="camera-frame">{camera?.image_url?<img src={`${api.baseUrl}${camera.image_url}`} alt="Latest field capture"/>:<EmptyState><Camera size={34}/>No camera image received</EmptyState>}</div><div className="camera-details"><span className="eyebrow">CAMERA STATUS</span><strong>{camera?.online?'ONLINE':'UNAVAILABLE'}</strong><p>{camera?.vision?.message||'No visual evidence available.'}</p></div></div></section>
  if(active==='alerts') return <section className="page-content"><SectionTitle eyebrow="ATTENTION QUEUE" title="Alert Center" detail="Backend-reported environmental events."/><div className="list-panel">{alerts.length?alerts.map(a=><div className="alert-row" key={a.alert_id||`${a.timestamp}-${a.message}`}><AlertTriangle size={18}/><div><strong>{a.hazard||'Environmental alert'}</strong><p>{a.message}</p></div><span className={`badge ${statusClass(a.severity)}`}>{a.severity}</span></div>):<EmptyState><CheckCircle2 size={30}/>No alerts received from backend.</EmptyState>}</div></section>
  if(active==='reports') return <Reports/>
  if(active==='map') return <section className="page-content"><SectionTitle eyebrow="FIELD COVERAGE" title="Monitoring Map" detail="Node locations reported by the backend."/><div className="map-placeholder"><Map size={42}/><strong>{devices.length?`${devices.length} node(s) reporting`:'No node coordinates available'}</strong><span>Map coordinates remain unavailable until devices provide location data.</span></div></section>
  if(active==='settings') return <section className="page-content"><SectionTitle eyebrow="SYSTEM PREFERENCES" title="Settings" detail="Dashboard preferences and connection status."/><div className="settings-panel"><div><span className="eyebrow">API BASE URL</span><strong>{api.baseUrl}</strong></div><div><span className="eyebrow">DATA SOURCE</span><strong>Flask API → Firebase Realtime Database</strong></div><div><span className="eyebrow">STALE WINDOW</span><strong>10 seconds</strong></div></div></section>
  const chart=history.map(x=>({time:formatTime(x.timestamp),temperature:Number(x.temperature)})).filter(x=>Number.isFinite(x.temperature))
  return <section className="page-content"><div className="hero-strip"><div><span className="eyebrow">{active==='overview'?'OPERATIONAL OVERVIEW':'LIVE TELEMETRY'}</span><h2>{online?`Monitoring ${data?.device_id||'active node'}`:'Waiting for sensor data'}</h2><p>{online?`Last reading received at ${formatTime(data?.timestamp)}.`:'No fresh sensor data is currently available.'}</p></div><button className="refresh-button" onClick={refresh}><RefreshCw size={16}/>Refresh</button></div><div className="summary-grid"><article><span className="eyebrow">OVERALL RISK</span><strong>{online?value(data?.overall_risk,0):'N/A'}<small>/100</small></strong><span className={`badge ${statusClass(online?data?.overall_status:'N/A')}`}>{online?data?.overall_status||'N/A':'N/A'}</span></article><article><span className="eyebrow">ACTIVE NODES</span><strong>{devices.filter(x=>x.online).length||'N/A'}</strong><span className="summary-muted">Actual reporting devices</span></article><article><span className="eyebrow">ALERTS</span><strong>{alerts.length}</strong><span className="summary-muted">Backend-reported events</span></article><article><span className="eyebrow">FORECAST</span><strong>{forecast?.forecast_available?forecast.predicted_status:'N/A'}</strong><span className="summary-muted">Next 6 hours</span></article></div><SectionTitle eyebrow="LIVE ENVIRONMENTAL TELEMETRY" title="Sensor readings" detail="Real-time values from the active monitoring node."/><div className="metric-grid">{metrics.map(item=><MetricCard item={item} data={data} online={online} key={item[1]}/>)}</div><SectionTitle eyebrow="CURRENT RISK INTELLIGENCE" title="Hazard assessment" detail="Official risk values are provided by the backend."/><div className="risk-grid">{riskItems.map(item=><RiskCard item={item} data={data} online={online} key={item[1]}/>)}</div><SectionTitle eyebrow="ENVIRONMENTAL TRENDS" title="History" detail="Real readings returned by the existing history API."/><div className="chart-panel"><div className="chart-heading"><div><span className="eyebrow">TEMPERATURE</span><strong>{chart.length?`${chart.at(-1).temperature.toFixed(1)} °C`:'N/A'}</strong></div><span>{history.length} reading(s)</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="tempFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1f8a70" stopOpacity={.35}/><stop offset="100%" stopColor="#1f8a70" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#dce7e2"/><XAxis dataKey="time" stroke="#738078" fontSize={11}/><YAxis stroke="#738078" fontSize={11}/><Tooltip/><Area type="monotone" dataKey="temperature" stroke="#1f8a70" fill="url(#tempFill)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></div></section>
}
export default function App(){ const [active,setActive]=useState('overview'),[mobileOpen,setMobileOpen]=useState(false),[theme,setTheme]=useState('light'),[data,setData]=useState(null),[backendOnline,setBackendOnline]=useState(false),[online,setOnline]=useState(false),[lastSeen,setLastSeen]=useState(null),[history,setHistory]=useState([]),[alerts,setAlerts]=useState([]),[forecast,setForecast]=useState(null),[camera,setCamera]=useState(null),[devices,setDevices]=useState([]),[error,setError]=useState(''); const refresh=async()=>{try{const [health,latest,h,a,f,c,d]=await Promise.all([api.get('/api/health'),api.get('/api/latest-data'),api.get('/api/history?limit=40'),api.get('/api/alerts'),api.get('/api/forecast'),api.get('/api/camera/latest'),api.get('/api/devices')]); const fresh=latest.online===true&&latest.data; setBackendOnline(health?.backend==='online');setOnline(Boolean(fresh));setData(fresh?latest.data:null);setLastSeen(fresh?latest.last_seen:latest.last_seen||null);setHistory(h.readings||[]);setAlerts(a.alerts||[]);setForecast(f);setCamera(c);setDevices(d.devices||[]);setError(health?.backend==='online'?'':'Backend unavailable')}catch(e){setBackendOnline(false);setOnline(false);setData(null);setError(e.message||'Unable to reach backend')}}; useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);useEffect(()=>{refresh();const timer=setInterval(refresh,3000);return()=>clearInterval(timer)},[]);const node=useMemo(()=>data?.device_id||devices.find(x=>x.online)?.device_id,[data,devices]);return <div className="app"><Sidebar active={active} setActive={id=>{setActive(id);setMobileOpen(false)}} online={online} device={node} alertCount={alerts.length} mobileOpen={mobileOpen}/><main><Header active={active} backendOnline={backendOnline} lastSeen={lastSeen} onMenu={()=>setMobileOpen(true)} theme={theme} setTheme={setTheme}/>{error&&<div className="error-banner"><AlertTriangle size={16}/>{error}</div>}<Content active={active} data={data} online={online} history={history} alerts={alerts} forecast={forecast} camera={camera} devices={devices} refresh={refresh}/></main></div> }